// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmJowmiJnM6cdXTZokHctS2OzeVrRYHwY',
    appId: '1:861031915467:android:af554390b31667391ee04e',
    messagingSenderId: '861031915467',
    projectId: 'app-dev-final-exam-46bc1',
    storageBucket: 'app-dev-final-exam-46bc1.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBixLgPPnGr7GV6iCSo2hgu2Txs9LrpvqI',
    appId: '1:861031915467:web:b6e09c3b4d29be411ee04e',
    messagingSenderId: '861031915467',
    projectId: 'app-dev-final-exam-46bc1',
    authDomain: 'app-dev-final-exam-46bc1.firebaseapp.com',
    storageBucket: 'app-dev-final-exam-46bc1.firebasestorage.app',
    measurementId: 'G-P4FQQN466Z',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtKBmFD0m180G-K-GjX8Ntu_O_jFC07z8',
    appId: '1:861031915467:ios:8d1fd3ca367388201ee04e',
    messagingSenderId: '861031915467',
    projectId: 'app-dev-final-exam-46bc1',
    storageBucket: 'app-dev-final-exam-46bc1.firebasestorage.app',
    androidClientId: '861031915467-7vq5344o3bvbcso452127jp3oulhgbf7.apps.googleusercontent.com',
    iosClientId: '861031915467-sgfbtq5je4le3rnevjdbvblsfbm359g1.apps.googleusercontent.com',
    iosBundleId: 'com.example.appDevFinalExam',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtKBmFD0m180G-K-GjX8Ntu_O_jFC07z8',
    appId: '1:861031915467:ios:8d1fd3ca367388201ee04e',
    messagingSenderId: '861031915467',
    projectId: 'app-dev-final-exam-46bc1',
    storageBucket: 'app-dev-final-exam-46bc1.firebasestorage.app',
    androidClientId: '861031915467-7vq5344o3bvbcso452127jp3oulhgbf7.apps.googleusercontent.com',
    iosClientId: '861031915467-sgfbtq5je4le3rnevjdbvblsfbm359g1.apps.googleusercontent.com',
    iosBundleId: 'com.example.appDevFinalExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBixLgPPnGr7GV6iCSo2hgu2Txs9LrpvqI',
    appId: '1:861031915467:web:9890a456ffb97fe01ee04e',
    messagingSenderId: '861031915467',
    projectId: 'app-dev-final-exam-46bc1',
    authDomain: 'app-dev-final-exam-46bc1.firebaseapp.com',
    storageBucket: 'app-dev-final-exam-46bc1.firebasestorage.app',
    measurementId: 'G-566FSGJKFB',
  );

}